### ISSUE TITLE
Add enum of client privileges

### ISSUE THREAD

**Issue by how-to-do-frontend** [Lekuruu/bancho-documentation#1]
I want to add the enum of client privileges used in the Login Permissions packet, and the User Presence packet.

ClientPrivileges.md
---
| Name        | Value |
|-------------|-------|
| Player        | 1        |
| Nominator | 2        |
| Supporter  | 4        |
| Owner        | 8        |
| Developer  | 16      |

> [!NOTE]
> The privileges are bit masked, so that they can be combined into one integer.

**Comment by Lekuruu** [comment]
Interesting that I haven't added this yet...

**Comment by Lekuruu** [comment]
Thank you for pointing it out!
